# name: Docker Image CI

# on:
#   push:
#     branches: [ "staging" ]
#   pull_request:
#     branches: [ "staging" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the repository
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Step 2: Log in to GHCR
#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: adhuldas
#           password: ${{ secrets.GHCR_PAT }}

#       # Step 3: Build the Docker image
#       - name: Build Docker image
#         run: |
#           IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}"
#           echo "Building Docker image: $IMAGE_NAME"
#           docker build . --file Dockerfile --tag $IMAGE_NAME

#       # Step 4: Push the Docker image
#       - name: Push Docker image to GHCR
#         run: |
#           IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}"
#           echo "Pushing Docker image: $IMAGE_NAME"
#           docker push $IMAGE_NAME
